making slave_basebackup more flexible

diff --git a/slave_basebackup b/slave_basebackup
--- a/slave_basebackup
+++ b/slave_basebackup
@@ -1,15 +1,55 @@
 #!/bin/bash
-if [ "$#" -eq 1 ] 
+usage()
+{
+cat << EOF
+usage: $0 options
+
+OPTIONS:
+   -h      Master server address
+   -U      The replication user defined in Master's pg_hba.conf file
+EOF
+}
+
+abort() 
+{
+  echo -e "\n>> Aborted pg_basebackup <<"
+}
+
+while getopts h:U: option
+do
+  case "${option}"
+  in
+    U) SLAVE_USER=${OPTARG};;
+    h) MASTER_ADDRESS=${OPTARG};;
+  esac
+done
+
+if [[ -z $SLAVE_USER ]] || [[ -z $MASTER_ADDRESS ]]
 then
-  echo "Creating backup directory if it doesn't exist (/var/lib/postgresql/9.1/backups)"
-  mkdir -p /var/lib/postgresql/9.1/backups
-  echo "Starting base backup."
-  #time pg_basebackup -h $1 -D /var/lib/postgresql/9.1/backups -U rep_user -v
-  time pg_basebackup -h $1 -D /var/lib/postgresql/9.1/slave-backups-tmp -U rep_user -v -Ft -z
-  tar --exclude=pg_log --exclude=pg_xlog -xvf /var/lib/postgresql/9.1/slave-backups-tmp/base.tar.gz -C /var/lib/postgresql/9.1/main
-  rm -rf /var/lib/postgresql/9.1/slave-backups-tmp
-  echo "Starting postgres in standby mode."
-  pg_ctlcluster 9.1 main restart
+  usage
+  exit 1
 else
-  echo "Task aborted: Provide the master host. (e.g. master_basebackup 192.168.1.180)"
+  echo "Starting pg_basebackup..."
+
+  read -p "This will replace all existing data in /var/lib/postgresql/9.1/main. ARE YOU SURE? [Y/n] " response
+
+  if [[ $response =~ ^[y|Y](es)?$ ]]
+  then
+    echo -e "\nRunning command: pg_basebackup -h $MASTER_ADDRESS -D /var/lib/postgresql/9.1/slave-backups-tmp -U $SLAVE_USER -v -Ft -z\n"
+    time pg_basebackup -h $MASTER_ADDRESS -D /var/lib/postgresql/9.1/slave-backups-tmp -U $SLAVE_USER -v -Ft -z
+    if [[ $? -eq 0 ]]
+    then
+      echo "\nUntarring file and moving data to /var/lib/postgresql/9.1/main"
+      tar --exclude=pg_log --exclude=pg_xlog -xvf /var/lib/postgresql/9.1/slave-backups-tmp/base.tar.gz -C /var/lib/postgresql/9.1/main
+      echo "\nRemoving basebackup tar file (cleaning up)"
+      rm -rf /var/lib/postgresql/9.1/slave-backups-tmp
+      echo "Starting postgres in standby mode."
+      pg_ctlcluster 9.1 main restart
+    else
+      abort
+    fi
+  else
+    abort
+  fi
+  exit 0
 fi
